name: Docker Build and Push

on:
  workflow_call:
    inputs:
      org_name:
        description: "Organization Name"
        required: true
        type: string
      image_name:
        description: "Docker image name"
        required: true
        type: string
      branch:
        description: "Branch to trigger on"
        required: false
        type: string
        default: main

    secrets:
      DIGITALOCEAN_USERNAME:
        required: true
      DIGITALOCEAN_ACCESS_TOKEN:
        required: true
      DIGITALOCEAN_ORG_NAME:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }} # Use the specified branch (default is 'main')

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to DigitalOcean Container Registry
      - name: Log in to DigitalOcean
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      # Step 4: Build the Docker image
      - name: Build Docker image
        env:
          IMAGE_TAG: "registry.digitalocean.com/${{ inputs.org_name }}/${{ inputs.image_name }}:${{ github.sha }}"
        run: |
          echo "Building Docker image: $IMAGE_TAG"
          docker build -t $IMAGE_TAG .

      # Step 5: Push the Docker image to DigitalOcean
      - name: Push Docker image to DigitalOcean
        env:
          IMAGE_TAG: "registry.digitalocean.com/${{ inputs.org_name }}/${{ inputs.image_name }}:${{ github.sha }}"
        run: |
          echo "Pushing Docker image: $IMAGE_TAG"
          docker push $IMAGE_TAG
