name: Docker Build and Push

on:
  workflow_call:
    inputs:
      org_name:
        description: "Organization Name"
        required: false
        type: string
        default: aimleap
      image_name:
        description: "Docker image name"
        required: true
        type: string
      branch:
        description: "Branch to trigger on"
        required: false
        type: string
        default: main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DigitalOcean
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_TAG="registry.digitalocean.com/${{ inputs.org_name }}/${{ inputs.image_name }}:${{ github.sha }}"
          docker build -t $IMAGE_TAG .

      - name: Push Docker image to DigitalOcean
        run: |
          IMAGE_TAG="registry.digitalocean.com/${{ inputs.org_name }}/${{ inputs.image_name }}:${{ github.sha }}"
          docker push $IMAGE_TAG
